---
spring:
  profiles: peer1
server:
  port: 9999
eureka:
  instance:
    hostname: peer1
    leaseRenewalIntervalInSeconds: 10
    lease-expiration-duration-in-seconds: 20
    metadataMap:
     zone: zone2
    
  client:
    serviceUrl:
      defaultZone: http://localhost:9998/eureka/,http://localhost:9999/eureka/
  server:
    registry-sync-retries: 2
    max-time-for-replication: 30
---
spring:
  profiles: peer2
server:
  port: 9998
  
eureka:
  instance:
    hostname: peer2
    leaseRenewalIntervalInSeconds: 10
    lease-expiration-duration-in-seconds: 20
    metadataMap:
     zone: zone1
    
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/,http://localhost:9998/eureka
    
  server:
    registry-sync-retries: 1
    disable-transparent-fallback-to-other-region: true
    
    max-time-for-replication: 300
  
     
logging:
  level:
    com.netflix.discovery: 'OFF'
    com.netflix.eureka: TRACE
    